# Generated by Django 6.0.1 on 2026-02-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='staff_profile',
            field=models.ImageField(blank=True, null=True, upload_to='staff_pic'),
        ),
    ]
