# Generated by Django 6.0.1 on 2026-02-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_alter_staffmodel_staff_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='is_active',
        ),
    ]
