# Generated by Django 6.0.1 on 2026-02-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_remove_bookingmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
