# Generated by Django 6.0.1 on 2026-02-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_staffmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='is_active',
        ),
    ]
