# Generated by Django 6.0.1 on 2026-02-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_remove_staffmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
