# Generated by Django 6.0.1 on 2026-02-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_staffmodel_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingmodel',
            unique_together={('staff', 'booking_date', 'booking_time')},
        ),
    ]
