# Generated by Django 6.0.1 on 2026-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_alter_bookingmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
